# Generated by Django 2.0.5 on 2018-08-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpmsdblog', '0003_auto_20180814_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='терапевт', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='unit',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
