# Generated by Django 2.0.5 on 2018-08-30 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpmsdblog', '0004_auto_20180814_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=300)),
                ('drug_form', models.CharField(max_length=300)),
                ('drug_quantity_type', models.CharField(max_length=300)),
                ('drug_quantity', models.IntegerField()),
                ('drug_date_updated', models.DateField(auto_now=True)),
                ('drug_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpmsdblog.Unit')),
            ],
        ),
    ]
